name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:nightly
      volumes:
        - .:/satysfi
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        run: |
          satysfi t/test.saty | tee t/got
          diff t/expected t/got
